# Generated by Django 2.0.6 on 2018-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='headpic',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
