# Generated by Django 2.0.6 on 2018-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('realname', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_acount',
            },
        ),
    ]
